### ISSUE TITLE
EfDb.cs no longer compiles with latest 6.0.100-rc.2.21505.57

### ISSUE THREAD

**Issue by RobertHenry6bev** [aspnet/Benchmarks#1703]
I upgrade my dotnet installation on linux to use  the latest6.0.100-rc.2.21505.57

I clone a new version of  aspnet/Benchmarks and it no longer compiles:

aspnet/benchmarks/src/BenchmarksApps/Kestrel/PlatformBenchmarks/Data/EfDb.cs(28,30): error CS1061: 'DbContextOptionsBuilder<ApplicationDbContext>' does not contain a definition for 'EnableThreadSafetyChecks' and no accessible extension method 'EnableThreadSafetyChecks' accepting a first argument of type 'DbContextOptionsBuilder<ApplicationDbContext>' could be found (are you missing a using directive or an assembly reference?) [/mnt/robhenry/dotnet_techempower/aspnet/benchmarks/src/BenchmarksApps/Kestrel/PlatformBenchmarks/PlatformBenchmarks.csproj]

The commit 9a1016271b25e94430274affb9f422427a4c2b39 is implicated.
That commit changes a method name under an ifdef sensitive to DOTNET 6.

**Comment by DamianEdwards** [comment]
Please reopen if you still have an issue.
